volumes:
  psql:
  build:
services:
  db:
    container_name: rest-kt-db
    image: postgres:15.8-alpine3.20
    environment:
      POSTGRES_DB: root
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      TZ: Asia/Tokyo
    volumes:
      - psql:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    ports: [5432:5432]
  builder:
    container_name: rest-kt-builder
    image: gradle:8.10.2-jdk17
    working_dir: /app
    volumes:
      - .:/app
      - build:/app/build
      - /app/.gradle
    command: gradle build --continuous --no-daemon
  runner:
    container_name: rest-kt-runner
    image: gradle:8.10.2-jdk17
    working_dir: /app
    volumes:
      - .:/app
      - build:/app/build
      - /app/.gradle
    command: gradle bootRun --no-daemon
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/root
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
    ports: [8080:8080]
    depends_on: [db, builder]
