volumes:
  psql:
  api-gradle:
  api-build:
services:
  db:
    container_name: rest-kt-db
    image: postgres:15.8-alpine3.20
    environment:
      POSTGRES_DB: root
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      TZ: Asia/Tokyo
    volumes:
      - psql:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
  api:
    container_name: rest-kt-api
    image: gradle:8.10.2-jdk17
    working_dir: /app
    volumes:
      - .:/app
      - api-gradle:/app/.gradle
      - api-build:/app/build
    command: gradle run --no-daemon
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/root
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
    ports: [8080:8080]
    depends_on: [db]
